/*
 * Swagger Studentcourse
 *
 * This is a sample server Studentcourse server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"github.com/gorilla/mux"
	"net/http"
	"strings"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v2/",
		Index,
	},

	Route{
		"CreateCourse",
		strings.ToUpper("Post"),
		"/v2/course",
		CreateCourse,
	},

	Route{
		"DeleteCourse",
		strings.ToUpper("Delete"),
		"/v2/course/{name}",
		DeleteCourse,
	},

	Route{
		"GetCourseByName",
		strings.ToUpper("Get"),
		"/v2/course/{name}",
		GetCourseByName,
	},

	Route{
		"UpdateCourse",
		strings.ToUpper("Put"),
		"/v2/course/{name}",
		UpdateCourse,
	},

	Route{
		"AddStudent",
		strings.ToUpper("Post"),
		"/v2/student",
		AddStudent,
	},

	Route{
		"DeleteStudent",
		strings.ToUpper("Delete"),
		"/v2/student/{studentId}",
		DeleteStudent,
	},

	Route{
		"GetStudentById",
		strings.ToUpper("Get"),
		"/v2/student/{studentId}",
		GetStudentById,
	},

	Route{
		"UpdateStudent",
		strings.ToUpper("Put"),
		"/v2/student",
		UpdateStudent,
	},

	Route{
		"UpdateStudentWithForm",
		strings.ToUpper("Post"),
		"/v2/student/{studentId}",
		UpdateStudentWithForm,
	},

	Route{
		"UploadFile",
		strings.ToUpper("Post"),
		"/v2/student/{studentId}/uploadImage",
		UploadFile,
	},

	Route{
		"CreateTeacher",
		strings.ToUpper("Post"),
		"/v2/teacher",
		CreateTeacher,
	},

	Route{
		"CreateTeachersWithArrayInput",
		strings.ToUpper("Post"),
		"/v2/teacher/createWithArray",
		CreateTeachersWithArrayInput,
	},

	Route{
		"CreateTeachersWithListInput",
		strings.ToUpper("Post"),
		"/v2/teacher/createWithList",
		CreateTeachersWithListInput,
	},

	Route{
		"DeleteTeacher",
		strings.ToUpper("Delete"),
		"/v2/teacher/{teachername}",
		DeleteTeacher,
	},

	Route{
		"GetTeacherByName",
		strings.ToUpper("Get"),
		"/v2/teacher/{teachername}",
		GetTeacherByName,
	},

	Route{
		"UpdateTeacher",
		strings.ToUpper("Put"),
		"/v2/teacher/{teachername}",
		UpdateTeacher,
	},
}
